api:
  product-service:
    uri: http://localhost:9004/product
  customer-service:
    uri: http://localhost:9003/customer
server:
  port: '9006'
spring:
  data:
    mongodb:
      database: bank
      port: '27017'
      host: localhost
